baseURL = "https://stevenmortimer.com/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "stevenmortimer.com"
theme = "hugo-sustain"
enableEmoji = true
googleAnalytics = "UA-98603021-1"
# disqusShortname = "iamwhatir"
canonifyURLs = true
pluralizelisttitles = false
paginate = 5
paginatePath = ""
rssLimit = 100
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Permalinks]
    blog = "/:slug"

[Author]
    name = "Steven M. Mortimer"
    email = "reportmort@gmail.com"

[Taxonomies]
    category = "categories"
    tag = "tags"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
      
[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]   
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10       
      
[blackfriday] 
    hrefTargetBlank = true      

[Params]
    intro = true
    author = "Steven M. Mortimer"
    headline = "Blog"
    description = "R Packages, Machine Learning, Salesforce, DoubleClick, et cetera."
    image = "img/headshot.png"
    avatar = "headshot.jpg"
    github = "StevenMMortimer"
    linkedin = "StevenMMortimer"
    twitter = "StevenMMortimer"
    stackoverflow = "users/5258043/steven-m-mortimer"
    kofi = "StevenMMortimer"
    email = "reportmort@gmail.com"
    opengraph = true
    twittercards = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    
	# Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  dateFormat = "January 2, 2006"
	
	# Enable global LaTeX math rendering?
	#   If false, you can enable it locally on a per page basis.
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "3.0.5"

	# Highlight.js options
  highlightjsVersion = "10.1.1"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yml", "py", "sh", "shell", "json"]
  highlightjsTheme = "vs"
  
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
    
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
    
[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
    
[[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/StevenMMortimer"
    weight = 5
    
[[menu.main]]
    name = "R-Bloggers"
    url = "https://www.r-bloggers.com/"
    weight = 6  
    